export const actionTypes = {
  FETCH_USER_DATA: 'FETCH_USER_DATA',
  FETCH_DASHBOARD: 'FETCH_DASHBOARD',
  SET_DASHBOARD_DATA: 'SET_DASHBOARD_DATA',
  FETCH_INVESTMENTS: 'FETCH_INVESTMENTS',
  LOADING_INVESTMENTS: 'LOADING_INVESTMENTS',
  SET_INVESTMENTS_DATA: 'SET_INVESTMENTS_DATA',
};
